version: '3'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Expose Grafana port on the host
    depends_on:
      - loki
    links:
      - loki

