apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grifana
  name: grifana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    run: grifana
  type: NodePort

